<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.props" />
	
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Version>5.2.1.0</Version>
		<AssemblyName>CodeShellCore.Moldster</AssemblyName>
		<AssemblyVersion>5.2.1.0</AssemblyVersion>
		<FileVersion>5.2.1.0</FileVersion>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<RootNamespace>CodeShellCore.Moldster</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Application\CodeShellCore.Application.csproj" />
		<ProjectReference Include="..\CodeShellCore.Moldster.Application.Contracts\CodeShellCore.Moldster.Application.Contracts.csproj" />
		<ProjectReference Include="..\CodeShellCore.Moldster.Domain\CodeShellCore.Moldster.Domain.csproj" />
		<ProjectReference Include="..\CodeShellCore.Notifications.Application.Contracts\CodeShellCore.Notifications.Application.Contracts.csproj" />
		<ProjectReference Include="..\CodeShellCore\CodeShellCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>
