<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <RootNamespace>CodeShellCore.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeShellCore.Domain.Shared\CodeShellCore.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
