<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <UserSecretsId>7953d2cb-aa18-4fa1-9781-ff1eb3c7476c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeShellCore.Application\CodeShellCore.Application.csproj" />
  </ItemGroup>

</Project>
