<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>7953d2cb-aa18-4fa1-9781-ff1eb3c7476c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Modularity\Templates\module_class_template.template" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Modularity\Templates\module_class_template.template" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeShellCore.Application\CodeShellCore.Application.csproj" />
    <ProjectReference Include="..\CodeShellCore.CliDispatch\CodeShellCore.CliDispatch.csproj" />
  </ItemGroup>

</Project>
