<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Version>5.2.0.0</Version>
		<AssemblyName>CodeShellCore.Reporting</AssemblyName>
		<AssemblyVersion>5.2.0.0</AssemblyVersion>
		<FileVersion>5.2.0.0</FileVersion>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReportViewerCore.NETCore" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Domain.Shared\CodeShellCore.Domain.Shared.csproj" />
	</ItemGroup>

</Project>
