<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>CodeShellCore.Domain.Shared</AssemblyName>
		<RootNamespace>CodeShellCore</RootNamespace>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore\CodeShellCore.csproj" />
	</ItemGroup>
</Project>
