//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShellCore.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeShellCore.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataSet Name=&quot;%Name%&quot;&gt;
        ///	&lt;Query&gt;
        ///		&lt;DataSourceName&gt;%DataSourceName%&lt;/DataSourceName&gt;
        ///		&lt;CommandText&gt;/* Local Query */&lt;/CommandText&gt;
        ///	&lt;/Query&gt;
        ///	&lt;Fields&gt;
        ///		%Fields%
        ///	&lt;/Fields&gt;
        ///&lt;/DataSet&gt;.
        /// </summary>
        public static string DataSetTemplate {
            get {
                return ResourceManager.GetString("DataSetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataSource Name=&quot;%Name%&quot;&gt;
        ///    &lt;ConnectionProperties&gt;
        ///		&lt;DataProvider&gt;System.Data.DataSet&lt;/DataProvider&gt;
        ///		&lt;ConnectString&gt;/* Local Connection */&lt;/ConnectString&gt;
        ///    &lt;/ConnectionProperties&gt;
        ///    &lt;rd:DataSourceID&gt;7c181f69-2fa1-4195-8673-4bbf91f5bbcf&lt;/rd:DataSourceID&gt;
        ///&lt;/DataSource&gt;.
        /// </summary>
        public static string DataSourceTemplate {
            get {
                return ResourceManager.GetString("DataSourceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;%Name%&quot;&gt;
        ///	&lt;DataField&gt;%Name%&lt;/DataField&gt;
        ///	&lt;rd:TypeName&gt;%Type%&lt;/rd:TypeName&gt;
        ///&lt;/Field&gt;.
        /// </summary>
        public static string FieldTemplate {
            get {
                return ResourceManager.GetString("FieldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Report xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot; xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot;&gt;
        ///  &lt;Body&gt;
        ///    &lt;Height&gt;3in&lt;/Height&gt;
        ///  &lt;/Body&gt;
        ///  
        ///  &lt;Page&gt;&lt;/Page&gt;
        ///  &lt;Width&gt;6.5in&lt;/Width&gt;
        ///  &lt;DataSources&gt;&lt;/DataSources&gt;
        ///  &lt;DataSets&gt;&lt;/DataSets&gt;
        ///&lt;/Report&gt;.
        /// </summary>
        public static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
    }
}
