<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\common.props" />
	
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>CodeShellCore.Domain</AssemblyName>
		<RootNamespace>CodeShellCore</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Domain.Shared\CodeShellCore.Domain.Shared.csproj" />
	</ItemGroup>

</Project>
