<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<RootNamespace>CodeShellCore.HealthCheck</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.EntityFramework\CodeShellCore.EntityFramework.csproj" />
		<ProjectReference Include="..\CodeshellCore.HealthCheck.Domain\CodeShellCore.HealthCheck.Domain.csproj" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2"></PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.2"></PackageReference>
	</ItemGroup>

</Project>
