<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>CodeShellCore.FileServer</RootNamespace>
		<AssemblyName>CodeShellCore.FileServer.EntityFramework</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.EntityFramework\CodeShellCore.EntityFramework.csproj" />
		<ProjectReference Include="..\CodeShellCore.FileServer.Domain\CodeShellCore.FileServer.Domain.csproj" />
	</ItemGroup>

</Project>
