<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>CodeShellCore.Application</AssemblyName>
		<RootNamespace>CodeShellCore</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Application.Contracts\CodeShellCore.Application.Contracts.csproj" />
		<ProjectReference Include="..\CodeShellCore.Domain\CodeShellCore.Domain.csproj" />
		<ProjectReference Include="..\CodeShellCore\CodeShellCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Http\Pushing\" />
	</ItemGroup>

</Project>
