<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\common.props" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>CodeShellCore.Application.Contracts</AssemblyName>
		<RootNamespace>CodeShellCore</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="DependecyInjection\**" />
		<EmbeddedResource Remove="DependecyInjection\**" />
		<None Remove="DependecyInjection\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Domain.Shared\CodeShellCore.Domain.Shared.csproj" />
		<ProjectReference Include="..\CodeShellCore\CodeShellCore.csproj" />
	</ItemGroup>


</Project>
