<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>CodeShellCore.Notifications</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Application\CodeShellCore.Application.csproj" />
		<ProjectReference Include="..\CodeShellCore.Notifications.Application.Contracts\CodeShellCore.Notifications.Application.Contracts.csproj" />
		<ProjectReference Include="..\CodeShellCore.Notifications.Domain\CodeShellCore.Notifications.Domain.csproj" />
	</ItemGroup>

</Project>
