<Project Sdk="Microsoft.NET.Sdk.Web">


  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Compile Remove="wwwroot\**" />
    <Content Remove="Logs\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="Logs\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="Logs\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeShellCore.Moldster.EntityFramework\CodeShellCore.Moldster.EntityFramework.csproj" />
    <ProjectReference Include="..\CodeShellCore.Moldster\CodeShellCore.Moldster.csproj" />
    <ProjectReference Include="..\CodeShellCore.Web.Razor\CodeShellCore.Web.Razor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
