<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>CodeShellCore.Notifications</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CodeShellCore.Domain\CodeShellCore.Domain.csproj" />
	  <ProjectReference Include="..\CodeShellCore.Notifications.Domain.Shared\CodeShellCore.Notifications.Domain.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Attachments\" />
	</ItemGroup>

</Project>
