//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShellCore.Moldster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeShellCore.Moldster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div [@loader]=&quot;ShowLoader ? &apos;shown&apos; : &apos;hidden&apos;&quot; class=&quot;loader-overlay&quot;&gt;
        ///    &lt;div class=&quot;loader&quot;&gt;&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div&gt;
        ///    &lt;div class=&quot;wrapper&quot;&gt;
        ///        &lt;top-bar #topBar&gt;&lt;/top-bar&gt;
        ///        &lt;div class=&quot;wrapper-side&quot; *ngIf=&quot;IsLoggedIn&quot;&gt;
        ///            &lt;navigation-side-bar&gt;&lt;/navigation-side-bar&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;wrapper-content&quot; [ngClass]=&quot;!IsLoggedIn?&apos;expanded&apos;:null&quot;&gt;
        ///            &lt;router-outlet&gt;&lt;/router-outlet&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div [ngClass]=&quot;Config.Locale==&apos;ar&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppComponent_cshtml {
            get {
                return ResourceManager.GetString("AppComponent_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AppComponent_ts {
            get {
                object obj = ResourceManager.GetObject("AppComponent_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { Injector, ViewChild, EventEmitter } from &quot;@angular/core&quot;;
        ///import { Title } from &quot;@angular/platform-browser&quot;;
        ///import { ServerConfigBase, Shell } from &quot;codeshell/core&quot;;
        ///import { IAppComponent } from &quot;codeshell/baseComponents&quot;;
        ///import { TestLoader } from &quot;codeshell/core&quot;;
        ///import { ServerConfig, AppInfo } from &quot;./ServerConfig&quot;;
        ///import { UserDTO } from &quot;codeshell/security&quot;;
        ///import { Stored } from &quot;codeshell/helpers&quot;;
        ///import { UseState } from &quot;./Models&quot;;
        ///
        ///
        ///
        ///export class AppComponentBase exten [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppComponentBase_ts {
            get {
                return ResourceManager.GetString("AppComponentBase_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;UseHotUpdate&quot;: true,
        ///  &quot;env&quot;: &quot;dev&quot;,
        ///  &quot;Services&quot;: {
        ///
        ///  },
        ///  &quot;AuthenticationEncKey&quot;: &quot;92929292929292932&quot;,
        ///  &quot;SuspendSignalR&quot;: &quot;true&quot;
        ///}.
        /// </summary>
        public static string appsettings_json {
            get {
                return ResourceManager.GetString("appsettings_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BaseComponent_ts {
            get {
                object obj = ResourceManager.GetObject("BaseComponent_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BaseModule_ts {
            get {
                object obj = ResourceManager.GetObject("BaseModule_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BasicComponent_ts {
            get {
                object obj = ResourceManager.GetObject("BasicComponent_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Boot_ts {
            get {
                object obj = ResourceManager.GetObject("Boot_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] codeshell {
            get {
                object obj = ResourceManager.GetObject("codeshell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Component_ts {
            get {
                object obj = ResourceManager.GetObject("Component_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///create function [dbo].[CompareVersion](
        ///	@v1 varchar(100),
        ///	@v2 varchar(100)
        ///)
        ///returns int
        ///AS
        ///begin
        ///declare @result int;
        ///
        ///    select @result=case 
        ///    when CONVERT(int, LEFT(@v1, CHARINDEX(&apos;.&apos;, @v1)-1)) &lt; CONVERT(int, LEFT(@v2, CHARINDEX(&apos;.&apos;, @v2)-1)) then 2
        ///    when CONVERT(int, LEFT(@v1, CHARINDEX(&apos;.&apos;, @v1)-1)) &gt; CONVERT(int, LEFT(@v2, CHARINDEX(&apos;.&apos;, @v2)-1)) then 1
        ///    when CONVERT(int, substring(@v1, CHARINDEX(&apos;.&apos;, @v1)+1, LEN(@v1))) &lt; CONVERT(int, substring(@v2, CHARINDEX(&apos;.&apos;, @v2)+1, LEN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] css {
            get {
                object obj = ResourceManager.GetObject("css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare module &quot;*.json&quot; {
        ///    const value: any;
        ///    export default value;
        ///}
        ///declare var jQuery: any;
        ///declare var $: any;
        ///.
        /// </summary>
        public static string declarations_d {
            get {
                return ResourceManager.GetString("declarations_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DomainModule_Lazy_ts {
            get {
                object obj = ResourceManager.GetObject("DomainModule_Lazy_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DomainModule_ts {
            get {
                object obj = ResourceManager.GetObject("DomainModule_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] img {
            get {
                object obj = ResourceManager.GetObject("img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE&gt;
        ///@model CodeShellCore.Web.Moldster.IndexModel
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;@Model.Title&lt;/title&gt;
        ///    &lt;base href=&quot;@Model.Config.BaseURL&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Armata&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Tajawal&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///
        ///    &lt;link href=&quot;~/css/plugins/animate.css&quot; rel=&quot;stylesheet&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Index_cshtml {
            get {
                return ResourceManager.GetString("Index_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] js {
            get {
                object obj = ResourceManager.GetObject("js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LocaleLoader_ts {
            get {
                object obj = ResourceManager.GetObject("LocaleLoader_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container&quot;&gt;
        ///    &lt;section class=&quot;row&quot;&gt;
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        &lt;div class=&quot;col-md-4 col-md-offset-4 col-sm-12 col-sm-offset-0 content-block&quot;&gt;
        ///            &lt;br class=&quot;not-mob&quot; /&gt;
        ///            &lt;div class=&quot;title-header text-center page-header&quot;&gt;
        ///                &lt;h2&gt;{{&apos;Words.Log__&apos; | translate}} &lt;span&gt;{{&apos;Words.In__&apos; | translate}}&lt;/span&gt;&lt;/h2&gt;
        ///            &lt;/div&gt;
        ///
        ///            &lt;form class=&quot;order-price &quot; #Form=&quot;ngForm&quot;&gt;
        ///                &lt;div class=&quot;row&quot;&gt;
        ///                    &lt;div clas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Login_html {
            get {
                return ResourceManager.GetString("Login_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { Component } from &apos;@angular/core&apos;;
        ///import { BaseComponent } from &apos;codeshell/baseComponents&apos;;
        ///import { Shell } from &apos;codeshell/core&apos;;
        ///import { AccountServiceBase } from &apos;codeshell/security&apos;;
        ///import { NoteType } from &apos;codeshell/helpers&apos;;
        ///
        ///@Component({ templateUrl: &quot;./Login.html&quot; })
        ///export class Login extends BaseComponent {
        ///
        ///    AccountService: AccountServiceBase = Shell.Injector.get(AccountServiceBase);
        ///    model: any = {};
        ///    GetPageId(): number { return 0; }
        ///
        ///    Login() {
        ///        th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Login_ts {
            get {
                return ResourceManager.GetString("Login_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ModalComponent_ts {
            get {
                object obj = ResourceManager.GetObject("ModalComponent_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Module_ts {
            get {
                object obj = ResourceManager.GetObject("Module_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;nav class=&quot;navbar-inverse nav-side&quot;&gt;
        ///
        ///    &lt;ul class=&quot;nav&quot;&gt;
        ///        &lt;li&gt;
        ///            &lt;a [routerLink]=&quot;[&apos;/&apos;]&quot;&gt;{{&apos;Words.Main&apos; | translate}}&lt;/a&gt;
        ///        &lt;/li&gt;
        ///        &lt;li *ngFor=&quot;let it of navs&quot;&gt;
        ///            &lt;a [routerLink]=&quot;&apos;/&apos;+it.url&quot; routerLinkActive=&quot;active&quot;&gt;{{&apos;Pages.&apos;+it.name | translate}}&lt;/a&gt;
        ///        &lt;/li&gt;
        ///    &lt;/ul&gt;
        ///&lt;/nav&gt;.
        /// </summary>
        public static string navigationSideBar_html {
            get {
                return ResourceManager.GetString("navigationSideBar_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { Component } from &quot;@angular/core&quot;;
        ///import { NavigationSideBarBase } from &quot;codeshell/baseComponents/NavigationSideBarBase&quot;;
        ///
        ///@Component({ templateUrl: &quot;./navigationSideBar.html&quot;, selector: &quot;navigation-side-bar&quot; })
        ///export class NavigationSideBar extends NavigationSideBarBase {
        ///
        ///}.
        /// </summary>
        public static string navigationSideBar_ts {
            get {
                return ResourceManager.GetString("navigationSideBar_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dependencies&quot;: {
        ///    &quot;@angular/core&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/forms&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/router&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/animations&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/common&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/platform-browser&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/platform-browser-dynamic&quot;: &quot;6.1.10&quot;,
        ///    &quot;@angular/cdk&quot;: &quot;6.4.7&quot;,
        ///    &quot;@angular/material&quot;: &quot;6.4.7&quot;,
        ///    &quot;@angular/material-moment-adapter&quot;: &quot;6.4.7&quot;,
        ///    &quot;@ng-select/ng-select&quot;: &quot;2.20.5&quot;,
        ///    &quot;@ngx-translate/core&quot;: &quot;10.0.2&quot;,
        ///    &quot;@aspnet/signalr&quot;: &quot;1.1.4&quot;,
        ///    &quot;angula [rest of string was truncated]&quot;;.
        /// </summary>
        public static string package_json {
            get {
                return ResourceManager.GetString("package_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ParentRoute_ts {
            get {
                object obj = ResourceManager.GetObject("ParentRoute_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Route_ts {
            get {
                object obj = ResourceManager.GetObject("Route_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Routes_ts {
            get {
                object obj = ResourceManager.GetObject("Routes_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { ServerConfigBase } from &quot;CodeShell/core&quot;;
        ///
        ///export class ServerConfig implements ServerConfigBase {
        ///    GoogleKey: string = &quot;&quot;;
        ///    BaseURL: string = &quot;&quot;;
        ///    Domain: string = &quot;&quot;;
        ///    Locale: string = &quot;&quot;;
        ///	Urls : any = {};
        ///
        ///    constructor() {
        ///        let item: HTMLElement = document.getElementById(&quot;view-data&quot;) as HTMLElement;
        ///        if (item)
        ///            Object.assign(this, JSON.parse(item.innerHTML));
        ///    }
        ///}.
        /// </summary>
        public static string ServerConfig_ts {
            get {
                return ResourceManager.GetString("ServerConfig_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Service_ts {
            get {
                object obj = ResourceManager.GetObject("Service_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ServicedBaseComponent_ts {
            get {
                object obj = ResourceManager.GetObject("ServicedBaseComponent_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SharedModule_ts {
            get {
                object obj = ResourceManager.GetObject("SharedModule_ts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;nav class=&quot;navbar navbar-static-top top-bar&quot;&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;navbar-brand&quot;&gt;
        ///            &lt;a (click)=&quot;Slide()&quot; class=&quot;mob&quot;&gt;
        ///                &lt;i class=&quot;fa fa-bars&quot;&gt;&lt;/i&gt;
        ///            &lt;/a&gt;
        ///            &lt;button (click)=&quot;ToggleNav()&quot; class=&quot;btn btn-default not-mob&quot;&gt;
        ///                &lt;i class=&quot;fa fa-bars&quot;&gt;&lt;/i&gt;
        ///            &lt;/button&gt;
        ///        &lt;/div&gt;
        ///
        ///        &lt;div class=&quot;pull-last&quot; *ngIf=&quot;isLoggedIn&quot;&gt;
        ///            &lt;ul class=&quot;nav navbar-nav&quot;&gt;
        ///                &lt;li style=&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string topBar_html {
            get {
                return ResourceManager.GetString("topBar_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { Component } from &quot;@angular/core&quot;;
        ///import { Shell, ServerConfigBase } from &quot;codeshell/core&quot;;
        ///
        ///import { BaseComponent } from &quot;codeshell/baseComponents&quot;;
        ///import { UserDTO } from &quot;codeshell/security&quot;;
        ///import { HttpClient } from &quot;@angular/common/http&quot;;
        ///import { ServerConfig, AppInfo } from &quot;Example/ServerConfig&quot;;
        ///import { AppComponentBase } from &quot;Example/AppComponentBase&quot;;
        ///import { Router } from &quot;@angular/router&quot;;
        ///import { TopBarBase } from &quot;codeshell/baseComponents/topBarBase&quot;;
        ///import { Tasks [rest of string was truncated]&quot;;.
        /// </summary>
        public static string topBar_ts {
            get {
                return ResourceManager.GetString("topBar_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;compilerOptions&quot;: {
        ///    &quot;module&quot;: &quot;es2015&quot;,
        ///    &quot;moduleResolution&quot;: &quot;node&quot;,
        ///    &quot;target&quot;: &quot;es5&quot;,
        ///    &quot;sourceMap&quot;: true,    
        ///    &quot;experimentalDecorators&quot;: true,
        ///    &quot;strictNullChecks&quot;: true,
        ///    &quot;emitDecoratorMetadata&quot;: true,
        ///    &quot;skipDefaultLibCheck&quot;: true,
        ///    &quot;skipLibCheck&quot;: true, // Workaround for https://github.com/angular/angular/issues/17863. Remove this if you upgrade to a fixed version of Angular.
        ///    &quot;strict&quot;: true,
        ///    &quot;lib&quot;: [ &quot;es6&quot;, &quot;dom&quot; ],
        ///    &quot;types&quot;: [ &quot;webpack-env&quot; ],
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tsconfig_json {
            get {
                return ResourceManager.GetString("tsconfig_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table Resources alter column DomainId bigint null;
        ///alter table Resources add ServiceName varchar(50) null;
        ///alter table PageCategories add DomainId bigint null;
        ///GO
        ///alter table Pages drop constraint FK_Pages_TenantDomains;
        ///alter table Pages add DomainId bigint null;
        ///alter table Pages add TenantId bigint null;
        ///GO
        ///
        ///update Pages 
        ///set
        ///	DomainId=td.DomainId,
        ///	TenantId=td.TenantId
        ///from Pages ps
        ///	join TenantDomains td on td.Id=ps.TenantDomainId;
        ///
        ///drop table TenantDomains;
        ///
        ///GO
        ///alter table Pag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string update_v2_1_0 {
            get {
                return ResourceManager.GetString("update_v2_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[NavigationGroups](
        ///	[Id] [bigint] NOT NULL,
        ///	[Name] [nvarchar](150) NULL,
        ///	[ParentId] [bigint] NULL,
        ///	[Chain] [nvarchar](max) NULL,
        ///	[CreatedOn] [datetime] NULL,
        ///	[CreatedBy] [bigint] NULL,
        ///	[UpdatedOn] [datetime] NULL,
        ///	[UpdatedBy] [bigint] NULL,
        /// CONSTRAINT [PK_NavigationGroups] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY] TEXTIMAGE_ON  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string update_v2_2_0 {
            get {
                return ResourceManager.GetString("update_v2_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE Tenants ADD Version VARCHAR(50) NULL;.
        /// </summary>
        public static string update_v2_5_0 {
            get {
                return ResourceManager.GetString("update_v2_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[PageCategoryParameters](
        ///	[Id] [bigint] NOT NULL,
        ///	[Name] [varchar](50) NULL,
        ///	[Type] [int] NOT NULL,
        ///	[DefaultValue] [varchar](max) NULL,
        ///	[PageCategoryId] [bigint] NOT NULL,
        ///	[CreatedOn] [datetime] NULL,
        ///	[CreatedBy] [bigint] NULL,
        ///	[UpdatedOn] [datetime] NULL,
        ///	[UpdatedBy] [bigint] NULL,
        /// CONSTRAINT [PK_PageCategoryParameters] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string update_v2_6_0 {
            get {
                return ResourceManager.GetString("update_v2_6_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CustomFields](
        ///	[Id] [bigint] NOT NULL,
        ///	[Name] [varchar](150) NULL,
        ///	[Type] [varchar](50) NULL,
        ///	[PageId] [bigint] NOT NULL,
        ///	[CreatedOn] [datetime] NULL,
        ///	[CreatedBy] [bigint] NULL,
        ///	[UpdatedOn] [datetime] NULL,
        ///	[UpdatedBy] [bigint] NULL,
        /// CONSTRAINT [PK_CustomFields] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string update_v2_8_0 {
            get {
                return ResourceManager.GetString("update_v2_8_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] webpack_config_js {
            get {
                object obj = ResourceManager.GetObject("webpack_config_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const path = require(&apos;path&apos;);
        ///const webpack = require(&apos;webpack&apos;);
        ///const ExtractTextPlugin = require(&apos;extract-text-webpack-plugin&apos;);
        ///const UglifyJsPlugin = require(&apos;uglifyjs-webpack-plugin&apos;);
        ///
        ///const treeShakableModules = [
        ///
        ///    &apos;@angular/common&apos;,
        ///    &apos;@angular/forms&apos;,
        ///    &apos;@angular/animations&apos;,
        ///    &apos;@angular/platform-browser&apos;,
        ///    &quot;@angular/platform-browser/animations&quot;,
        ///    &apos;@angular/platform-browser-dynamic&apos;,
        ///    &apos;@angular/router&apos;,
        ///
        ///    &apos;@angular/compiler&apos;,
        ///
        ///    &apos;@angular/material&apos;,
        ///    &quot;@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string webpack_config_vendor_js {
            get {
                return ResourceManager.GetString("webpack_config_vendor_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] webpack_tenant_js {
            get {
                object obj = ResourceManager.GetObject("webpack_tenant_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] webpack_tenant_js_bat {
            get {
                object obj = ResourceManager.GetObject("webpack_tenant_js_bat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] webpack_tenant_js_json {
            get {
                object obj = ResourceManager.GetObject("webpack_tenant_js_json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const path = require(&apos;path&apos;);
        ///const webpack = require(&apos;webpack&apos;);
        ///const CheckerPlugin = require(&apos;awesome-typescript-loader&apos;).CheckerPlugin;
        ///const ExtractTextPlugin = require(&apos;extract-text-webpack-plugin&apos;);
        ///
        ///module.exports = function WebpackSharedConfig(env) {
        ///    const isDevBuild = !(env &amp;&amp; env.prod);
        ///    const app = env.app ? env.app + &quot;-&quot; : &quot;&quot;;
        ///    const version = isDevBuild ? &quot;dev&quot; : &quot;v&quot; + (env.version ? env.version : &quot;1.0.0.0&quot;)
        ///    const clientBundleOutputDir = &apos;./wwwroot/dist&apos;;
        ///    return {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WebPackSharedConfig_js {
            get {
                return ResourceManager.GetString("WebPackSharedConfig_js", resourceCulture);
            }
        }
    }
}
