<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	  <RootNamespace>CodeShellCore.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeShellCore.Notifications.Application.Contracts\CodeShellCore.Notifications.Application.Contracts.csproj" />
    <ProjectReference Include="..\CodeShellCore.Web\CodeShellCore.Web.csproj" />
  </ItemGroup>

</Project>
