// <auto-generated />
using System;
using CodeShellCore.Moldster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeShellCore.Moldster.Migrations
{
    [DbContext(typeof(MoldsterContext))]
    partial class MoldsterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CodeShellCore.Moldster.App", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DashboardUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Client", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Identifier")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Secret")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Control", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ControlType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DesignParameters")
                        .HasColumnType("ntext");

                    b.Property<string>("Identifier")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("PageCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentControl")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PageCategoryId");

                    b.HasIndex("ParentControl");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ControlValidator", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ControlId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("ValidatorId");

                    b.ToTable("ControlValidators");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.CustomField", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.CustomText", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Locale")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CustomTexts");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Domain", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Chain")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameChain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.NavigationGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Chain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("NavigationGroups");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.NavigationPage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<long>("NavigationGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("NavigationGroupId");

                    b.HasIndex("PageId");

                    b.ToTable("NavigationPages");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Page", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Apps")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("CanEmbed")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("DefaultAccessibility")
                        .HasColumnType("int");

                    b.Property<long>("DomainId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasRoute")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHomePage")
                        .HasColumnType("bit");

                    b.Property<string>("Layout")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("PageCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrivilegeType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ResourceActionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("RouteParameters")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("SourceCollectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecialPermission")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ViewParams")
                        .HasColumnType("ntext");

                    b.Property<string>("ViewPath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("PageCategoryId");

                    b.HasIndex("ResourceActionId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SourceCollectionId");

                    b.HasIndex("TenantId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseComponent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("DomainId")
                        .HasColumnType("bigint");

                    b.Property<string>("Layout")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ViewPath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("ResourceId");

                    b.ToTable("PageCategories");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategoryParameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("PageCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PageCategoryId");

                    b.ToTable("PageCategoryParameters");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageControl", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte>("Accessability")
                        .HasColumnType("tinyint");

                    b.Property<long>("ControlId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Persistent")
                        .HasColumnType("bit");

                    b.Property<long?>("SourceCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("PageId");

                    b.HasIndex("SourceCollectionId");

                    b.ToTable("PageControls");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageControlValidator", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long>("PageControlId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<long>("ValidatorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PageControlId");

                    b.HasIndex("ValidatorId");

                    b.ToTable("PageControlValidators");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageParameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("LinkedPageId")
                        .HasColumnType("bigint");

                    b.Property<long>("PageCategoryParameterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("UseDefault")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PageCategoryParameterId");

                    b.HasIndex("PageId");

                    b.ToTable("PageParameters");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageRoute", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddUrl")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("DetailsUrl")
                        .HasColumnType("bigint");

                    b.Property<long?>("EditUrl")
                        .HasColumnType("bigint");

                    b.Property<long?>("ListUrl")
                        .HasColumnType("bigint");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageRoutes");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Resource", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("DomainId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceAction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TenantId");

                    b.ToTable("ResourceActions");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceCollection", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceCollections");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceCollectionCondition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<long?>("DomainEntityCollectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Property")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DomainEntityCollectionId");

                    b.ToTable("ResourceCollectionConditions");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MainComponentBase")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LogonName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Validator", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CalendarType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("MaxValue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("MinValue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Validators");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.App", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Tenant", "Tenant")
                        .WithMany("Apps")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_TenantApps_Tenants")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Control", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.PageCategory", "PageCategory")
                        .WithMany("Controls")
                        .HasForeignKey("PageCategoryId")
                        .HasConstraintName("FK_Controls_PageCategories")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CodeShellCore.Moldster.Control", "ParentControlNavigation")
                        .WithMany("InverseParentControlNavigation")
                        .HasForeignKey("ParentControl")
                        .HasConstraintName("FK_PageControls_PageControls");

                    b.Navigation("PageCategory");

                    b.Navigation("ParentControlNavigation");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ControlValidator", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Control", "Control")
                        .WithMany("ControlValidators")
                        .HasForeignKey("ControlId")
                        .HasConstraintName("FK_ControlValidators_Controls")
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Validator", "Validator")
                        .WithMany("ControlValidators")
                        .HasForeignKey("ValidatorId")
                        .HasConstraintName("FK_ControlValidators_Validators")
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Validator");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.CustomField", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Page", "Page")
                        .WithMany("CustomFields")
                        .HasForeignKey("PageId")
                        .HasConstraintName("FK_CustomFields_Pages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.CustomText", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Tenant", "Tenant")
                        .WithMany("CustomTexts")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_CustomTexts_Tenants")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.NavigationPage", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.NavigationGroup", "NavigationGroup")
                        .WithMany("NavigationPages")
                        .HasForeignKey("NavigationGroupId")
                        .HasConstraintName("FK_NavigationPages_NavigationGroups")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Page", "Page")
                        .WithMany("NavigationPages")
                        .HasForeignKey("PageId")
                        .HasConstraintName("FK_NavigationPages_Pages")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NavigationGroup");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Page", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Domain", "Domain")
                        .WithMany("Pages")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("FK_Pages_Domains")
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.PageCategory", "PageCategory")
                        .WithMany("Pages")
                        .HasForeignKey("PageCategoryId")
                        .HasConstraintName("FK_Pages_PageCategories");

                    b.HasOne("CodeShellCore.Moldster.ResourceAction", "ResourceAction")
                        .WithMany("Pages")
                        .HasForeignKey("ResourceActionId")
                        .HasConstraintName("FK_Pages_ResourceActions");

                    b.HasOne("CodeShellCore.Moldster.Resource", "Resource")
                        .WithMany("Pages")
                        .HasForeignKey("ResourceId")
                        .HasConstraintName("FK_Pages_Resources");

                    b.HasOne("CodeShellCore.Moldster.ResourceCollection", "SourceCollection")
                        .WithMany("Pages")
                        .HasForeignKey("SourceCollectionId")
                        .HasConstraintName("FK_Pages_DomainEntityCollections1");

                    b.HasOne("CodeShellCore.Moldster.Tenant", "Tenant")
                        .WithMany("Pages")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Pages_Tenants")
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("PageCategory");

                    b.Navigation("Resource");

                    b.Navigation("ResourceAction");

                    b.Navigation("SourceCollection");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategory", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Domain", "Domain")
                        .WithMany("PageCategories")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("FK_PageCategories_Domains");

                    b.HasOne("CodeShellCore.Moldster.Resource", "Resource")
                        .WithMany("PageCategories")
                        .HasForeignKey("ResourceId")
                        .HasConstraintName("FK_PageCategories_Resources");

                    b.Navigation("Domain");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategoryParameter", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.PageCategory", "PageCategory")
                        .WithMany("PageCategoryParameters")
                        .HasForeignKey("PageCategoryId")
                        .HasConstraintName("FK_PageCategoryParameters_PageCategories")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageCategory");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageControl", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Control", "Control")
                        .WithMany("PageControls")
                        .HasForeignKey("ControlId")
                        .HasConstraintName("FK_PageControls_Controls")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Page", "Page")
                        .WithMany("PageControls")
                        .HasForeignKey("PageId")
                        .HasConstraintName("FK_PageControls_Pages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.ResourceCollection", "SourceCollection")
                        .WithMany("PageControls")
                        .HasForeignKey("SourceCollectionId")
                        .HasConstraintName("FK_PageControls_DomainEntityCollections");

                    b.Navigation("Control");

                    b.Navigation("Page");

                    b.Navigation("SourceCollection");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageControlValidator", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.PageControl", "PageControl")
                        .WithMany("PageControlValidators")
                        .HasForeignKey("PageControlId")
                        .HasConstraintName("FK_PageControlValidators_PageControls")
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Validator", "Validator")
                        .WithMany("PageControlValidators")
                        .HasForeignKey("ValidatorId")
                        .HasConstraintName("FK_PageControlValidators_Validators")
                        .IsRequired();

                    b.Navigation("PageControl");

                    b.Navigation("Validator");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageParameter", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.PageCategoryParameter", "PageCategoryParameter")
                        .WithMany("PageParameters")
                        .HasForeignKey("PageCategoryParameterId")
                        .HasConstraintName("FK_PageParameters_PageCategoryParameters")
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Page", "Page")
                        .WithMany("PageParameters")
                        .HasForeignKey("PageId")
                        .HasConstraintName("FK_PageParameters_Pages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("PageCategoryParameter");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageRoute", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Page", "Page")
                        .WithMany("PageRoutes")
                        .HasForeignKey("PageId")
                        .HasConstraintName("FK_PageRoutes_Pages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Resource", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Domain", "Domain")
                        .WithMany("Resources")
                        .HasForeignKey("DomainId")
                        .HasConstraintName("FK_Resources_Domains");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceAction", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Resource", "Resource")
                        .WithMany("ResourceActions")
                        .HasForeignKey("ResourceId")
                        .HasConstraintName("FK_ResourceActions_Resources")
                        .IsRequired();

                    b.HasOne("CodeShellCore.Moldster.Tenant", "Tenant")
                        .WithMany("ResourceActions")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_ResourceActions_Tenants")
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceCollection", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.Resource", "Resource")
                        .WithMany("ResourceCollections")
                        .HasForeignKey("ResourceId")
                        .HasConstraintName("FK_ResourceCollections_Resources")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceCollectionCondition", b =>
                {
                    b.HasOne("CodeShellCore.Moldster.ResourceCollection", "DomainEntityCollection")
                        .WithMany("ResourceCollectionConditions")
                        .HasForeignKey("DomainEntityCollectionId")
                        .HasConstraintName("FK_EntityCollectionConditions_DomainEntityCollections");

                    b.Navigation("DomainEntityCollection");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Control", b =>
                {
                    b.Navigation("ControlValidators");

                    b.Navigation("InverseParentControlNavigation");

                    b.Navigation("PageControls");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Domain", b =>
                {
                    b.Navigation("PageCategories");

                    b.Navigation("Pages");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.NavigationGroup", b =>
                {
                    b.Navigation("NavigationPages");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Page", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("NavigationPages");

                    b.Navigation("PageControls");

                    b.Navigation("PageParameters");

                    b.Navigation("PageRoutes");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategory", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("PageCategoryParameters");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageCategoryParameter", b =>
                {
                    b.Navigation("PageParameters");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.PageControl", b =>
                {
                    b.Navigation("PageControlValidators");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Resource", b =>
                {
                    b.Navigation("PageCategories");

                    b.Navigation("Pages");

                    b.Navigation("ResourceActions");

                    b.Navigation("ResourceCollections");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceAction", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.ResourceCollection", b =>
                {
                    b.Navigation("PageControls");

                    b.Navigation("Pages");

                    b.Navigation("ResourceCollectionConditions");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Tenant", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("CustomTexts");

                    b.Navigation("Pages");

                    b.Navigation("ResourceActions");
                });

            modelBuilder.Entity("CodeShellCore.Moldster.Validator", b =>
                {
                    b.Navigation("ControlValidators");

                    b.Navigation("PageControlValidators");
                });
#pragma warning restore 612, 618
        }
    }
}
