<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>CodeShellCore.Web</AssemblyName>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		
		<PackageReference Include="Microsoft.AspNetCore.Components" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeShellCore.Application.Contracts\CodeShellCore.Application.Contracts.csproj" />
		<ProjectReference Include="..\CodeShellCore\CodeShellCore.csproj" />
	</ItemGroup>

</Project>
